name: Docker

on:
  push:
    branches:
      - main
      
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  publish-to-docker-hub:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: bspaulding/braylor
        tag_with_ref: true
